name = "j2ms"
license = "MIT"
licenselink = "https://github.com/MichaelSchmidle/j2.ms/blob/master/LICENSE"
description = "Theme for the j2.ms website"
homepage = "http://j2.ms/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Michael Schmidle"
  homepage = "https://blog.ypertex.com/"
